<?php

namespace DomotiqueBundle\Repository;

/**
 * Sous_moduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sous_moduleRepository extends \Doctrine\ORM\EntityRepository
{
}
